# Generated by Django 4.2.3 on 2023-08-22 15:40

from django.db import migrations, models
import news.models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_news"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(
                max_length=200,
                validators=[news.models.validators.validate_title],
            ),
        ),
    ]
